- name: Install mariadb
  hosts: all
  become: yes
  tasks:
    - name: Install mariadb-server package
      package:
        name: mariadb-server
        state: present

    - name: Verify mariadb-server installed
      command: rpm -q mariadb-server
      register: result

    - debug:
        var: result.stdout
