- name: Slack API(chat.postMessage) 메시지 전송 예제
  hosts: localhost
  gather_facts: false
  vars:
    slack_token: "xoxb-8955248307747-8962170853094-Ewyhoxaxt6GxQ9vZ6IXff498"
    slack_channel: "#app-alerts"  # 실제 Bot이 초대된 채널명
    slack_message: "Hello, World!"
  tasks:
    - name: Send Slack message using chat.postMessage API
      uri:
        url: "https://slack.com/api/chat.postMessage"
        method: POST
        headers:
          Authorization: "Bearer {{ slack_token }}"
          Content-Type: "application/json"
        body: |
          {
            "channel": "{{ slack_channel }}",
            "text": "{{ slack_message }}"
          }
        body_format: json
