- name: Notify Slack when AAP job completes
  hosts: node1.localdomain
  gather_facts: false
  vars:
    slack_webhook_url: "https://hooks.slack.com/services/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"
    message: |
      *ðŸ“¢ AAP Job Notification*
      - ìž‘ì—… ì´ë¦„: {{ job_template_name | default('N/A') }}
      - ìƒíƒœ: {{ job_status | default('N/A') }}
      - ì‹œìž‘: {{ job_start | default('N/A') }}
      - ì¢…ë£Œ: {{ job_end | default('N/A') }}
  tasks:
    - name: Send message to Slack
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "text": "{{ message }}"
          }
        body_format: json
