- name: Slack API(chat.postMessage) 메시지 전송 예제
  hosts: localhost
  gather_facts: false
  vars:
    # 여기에 직접 변수 입력해도 되고, extra_vars/인벤토리 등 외부에서 받아도 됩니다
    # slack_token: "xoxb-여기에-슬랙-토큰"
    # slack_channel: "#aap-alerts"
    slack_message: "Hello, World!"
  tasks:
    - name: Send Slack message using chat.postMessage API
      uri:
        url: "https://slack.com/api/chat.postMessage"
        method: POST
        headers:
          Authorization: "Bearer {{ slack_token }}"
          Content-Type: "application/json"
        body: |
          {
            "channel": "{{ slack_channel }}",
            "text": "{{ slack_message }}"
          }
        body_format: json
      register: slack_result

    - name: Slack 응답 결과 출력(debug)
      debug:
        var: slack_result.json
